[tool.isort]
profile = "black"
src_paths = ["projects_pipeline", "test"]
color_output = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_between_types = 1
use_parentheses = true
